use crate::icons::{IconId, IconTheme};

#[derive(Debug, Default)]
pub struct CharmedIconTheme;

impl IconTheme for CharmedIconTheme {
    const ICONS: &'static [(IconId, &'static [u8])] = &[
        (
            IconId::FILE,
            include_bytes!("../../assets/charmed_icons/_file.b64"),
        ),
        (
            IconId::FOLDER,
            include_bytes!("../../assets/charmed_icons/_folder.b64"),
        ),
        (
            IconId::FOLDER_OPEN,
            include_bytes!("../../assets/charmed_icons/_folder_open.b64"),
        ),
        (
            IconId::ASSEMBLY,
            include_bytes!("../../assets/charmed_icons/assembly.b64"),
        ),
        (
            IconId::ASTRO_CONFIG,
            include_bytes!("../../assets/charmed_icons/astro-config.b64"),
        ),
        (
            IconId::ASTRO,
            include_bytes!("../../assets/charmed_icons/astro.b64"),
        ),
        (
            IconId::AUDIO,
            include_bytes!("../../assets/charmed_icons/audio.b64"),
        ),
        (
            IconId::BINARY,
            include_bytes!("../../assets/charmed_icons/binary.b64"),
        ),
        (
            IconId::BUN_LOCK,
            include_bytes!("../../assets/charmed_icons/bun-lock.b64"),
        ),
        (
            IconId::BUN,
            include_bytes!("../../assets/charmed_icons/bun.b64"),
        ),
        (
            IconId::C,
            include_bytes!("../../assets/charmed_icons/c.b64"),
        ),
        (
            IconId::C_HEADER,
            include_bytes!("../../assets/charmed_icons/c-header.b64"),
        ),
        (
            IconId::CHANGELOG,
            include_bytes!("../../assets/charmed_icons/changelog.b64"),
        ),
        (
            IconId::CODE_OF_CONDUCT,
            include_bytes!("../../assets/charmed_icons/code-of-conduct.b64"),
        ),
        (
            IconId::CODEOWNERS,
            include_bytes!("../../assets/charmed_icons/codeowners.b64"),
        ),
        (
            IconId::CONFIG,
            include_bytes!("../../assets/charmed_icons/config.b64"),
        ),
        (
            IconId::CPP_HEADER,
            include_bytes!("../../assets/charmed_icons/cpp-header.b64"),
        ),
        (
            IconId::CPP,
            include_bytes!("../../assets/charmed_icons/cpp.b64"),
        ),
        (
            IconId::CS,
            include_bytes!("../../assets/charmed_icons/cs.b64"),
        ),
        (
            IconId::CSS,
            include_bytes!("../../assets/charmed_icons/css.b64"),
        ),
        (
            IconId::CSS3,
            include_bytes!("../../assets/charmed_icons/css3.b64"),
        ),
        (
            IconId::CSV,
            include_bytes!("../../assets/charmed_icons/csv.b64"),
        ),
        (
            IconId::DART,
            include_bytes!("../../assets/charmed_icons/dart.b64"),
        ),
        (
            IconId::DATABASE,
            include_bytes!("../../assets/charmed_icons/database.b64"),
        ),
        (
            IconId::DOCKER,
            include_bytes!("../../assets/charmed_icons/docker.b64"),
        ),
        (
            IconId::DRIZZLE_ORM,
            include_bytes!("../../assets/charmed_icons/drizzle-orm.b64"),
        ),
        (
            IconId::ESLINT,
            include_bytes!("../../assets/charmed_icons/eslint.b64"),
        ),
        (
            IconId::EVENT,
            include_bytes!("../../assets/charmed_icons/event.b64"),
        ),
        (
            IconId::FOLDER_ADMIN,
            include_bytes!("../../assets/charmed_icons/folder_admin.b64"),
        ),
        (
            IconId::FOLDER_ADMIN_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_admin_open.b64"),
        ),
        (
            IconId::FOLDER_ANIMATION,
            include_bytes!("../../assets/charmed_icons/folder_animation.b64"),
        ),
        (
            IconId::FOLDER_ANIMATION_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_animation_open.b64"),
        ),
        (
            IconId::FOLDER_ASSETS,
            include_bytes!("../../assets/charmed_icons/folder_assets.b64"),
        ),
        (
            IconId::FOLDER_ASSETS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_assets_open.b64"),
        ),
        (
            IconId::FOLDER_AUDIO,
            include_bytes!("../../assets/charmed_icons/folder_audio.b64"),
        ),
        (
            IconId::FOLDER_AUDIO_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_audio_open.b64"),
        ),
        (
            IconId::FOLDER_AUTH,
            include_bytes!("../../assets/charmed_icons/folder_auth.b64"),
        ),
        (
            IconId::FOLDER_AUTH_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_auth_open.b64"),
        ),
        (
            IconId::FOLDER_BENCHMARK,
            include_bytes!("../../assets/charmed_icons/folder_benchmark.b64"),
        ),
        (
            IconId::FOLDER_BENCHMARK_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_benchmark_open.b64"),
        ),
        (
            IconId::FOLDER_BIN,
            include_bytes!("../../assets/charmed_icons/folder_bin.b64"),
        ),
        (
            IconId::FOLDER_BIN_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_bin_open.b64"),
        ),
        (
            IconId::FOLDER_BUILDER,
            include_bytes!("../../assets/charmed_icons/folder_builder.b64"),
        ),
        (
            IconId::FOLDER_BUILDER_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_builder_open.b64"),
        ),
        (
            IconId::FOLDER_CAMERA,
            include_bytes!("../../assets/charmed_icons/folder_camera.b64"),
        ),
        (
            IconId::FOLDER_CAMERA_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_camera_open.b64"),
        ),
        (
            IconId::FOLDER_CHANGESETS,
            include_bytes!("../../assets/charmed_icons/folder_changesets.b64"),
        ),
        (
            IconId::FOLDER_CHANGESETS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_changesets_open.b64"),
        ),
        (
            IconId::FOLDER_CLIENT,
            include_bytes!("../../assets/charmed_icons/folder_client.b64"),
        ),
        (
            IconId::FOLDER_CLIENT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_client_open.b64"),
        ),
        (
            IconId::FOLDER_COMMANDS,
            include_bytes!("../../assets/charmed_icons/folder_commands.b64"),
        ),
        (
            IconId::FOLDER_COMMANDS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_commands_open.b64"),
        ),
        (
            IconId::FOLDER_COMPONENT,
            include_bytes!("../../assets/charmed_icons/folder_component.b64"),
        ),
        (
            IconId::FOLDER_COMPONENT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_component_open.b64"),
        ),
        (
            IconId::FOLDER_CONFIG,
            include_bytes!("../../assets/charmed_icons/folder_config.b64"),
        ),
        (
            IconId::FOLDER_CONFIG_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_config_open.b64"),
        ),
        (
            IconId::FOLDER_CONNECTION,
            include_bytes!("../../assets/charmed_icons/folder_connection.b64"),
        ),
        (
            IconId::FOLDER_CONNECTION_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_connection_open.b64"),
        ),
        (
            IconId::FOLDER_CONSTANT,
            include_bytes!("../../assets/charmed_icons/folder_constant.b64"),
        ),
        (
            IconId::FOLDER_CONSTANT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_constant_open.b64"),
        ),
        (
            IconId::FOLDER_CONTENT,
            include_bytes!("../../assets/charmed_icons/folder_content.b64"),
        ),
        (
            IconId::FOLDER_CONTENT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_content_open.b64"),
        ),
        (
            IconId::FOLDER_CONTEXT,
            include_bytes!("../../assets/charmed_icons/folder_context.b64"),
        ),
        (
            IconId::FOLDER_CONTEXT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_context_open.b64"),
        ),
        (
            IconId::FOLDER_COVERAGE,
            include_bytes!("../../assets/charmed_icons/folder_coverage.b64"),
        ),
        (
            IconId::FOLDER_COVERAGE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_coverage_open.b64"),
        ),
        (
            IconId::FOLDER_DATABASE,
            include_bytes!("../../assets/charmed_icons/folder_database.b64"),
        ),
        (
            IconId::FOLDER_DATABASE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_database_open.b64"),
        ),
        (
            IconId::FOLDER_DIST,
            include_bytes!("../../assets/charmed_icons/folder_dist.b64"),
        ),
        (
            IconId::FOLDER_DIST_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_dist_open.b64"),
        ),
        (
            IconId::FOLDER_DOCS,
            include_bytes!("../../assets/charmed_icons/folder_docs.b64"),
        ),
        (
            IconId::FOLDER_DOCS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_docs_open.b64"),
        ),
        (
            IconId::FOLDER_EFFECTS,
            include_bytes!("../../assets/charmed_icons/folder_effects.b64"),
        ),
        (
            IconId::FOLDER_EFFECTS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_effects_open.b64"),
        ),
        (
            IconId::FOLDER_ERROR,
            include_bytes!("../../assets/charmed_icons/folder_error.b64"),
        ),
        (
            IconId::FOLDER_ERROR_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_error_open.b64"),
        ),
        (
            IconId::FOLDER_EVENT,
            include_bytes!("../../assets/charmed_icons/folder_event.b64"),
        ),
        (
            IconId::FOLDER_EVENT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_event_open.b64"),
        ),
        (
            IconId::FOLDER_FONTS,
            include_bytes!("../../assets/charmed_icons/folder_fonts.b64"),
        ),
        (
            IconId::FOLDER_FONTS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_fonts_open.b64"),
        ),
        (
            IconId::FOLDER_FUNCTION,
            include_bytes!("../../assets/charmed_icons/folder_function.b64"),
        ),
        (
            IconId::FOLDER_FUNCTION_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_function_open.b64"),
        ),
        (
            IconId::FOLDER_GITHUB,
            include_bytes!("../../assets/charmed_icons/folder_github.b64"),
        ),
        (
            IconId::FOLDER_GITHUB_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_github_open.b64"),
        ),
        (
            IconId::FOLDER_HOOKS,
            include_bytes!("../../assets/charmed_icons/folder_hooks.b64"),
        ),
        (
            IconId::FOLDER_HOOKS_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_hooks_open.b64"),
        ),
        (
            IconId::FOLDER_IMAGE,
            include_bytes!("../../assets/charmed_icons/folder_image.b64"),
        ),
        (
            IconId::FOLDER_IMAGE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_image_open.b64"),
        ),
        (
            IconId::FOLDER_INPUT,
            include_bytes!("../../assets/charmed_icons/folder_input.b64"),
        ),
        (
            IconId::FOLDER_INPUT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_input_open.b64"),
        ),
        (
            IconId::FOLDER_JAVASCRIPT,
            include_bytes!("../../assets/charmed_icons/folder_javascript.b64"),
        ),
        (
            IconId::FOLDER_JAVASCRIPT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_javascript_open.b64"),
        ),
        (
            IconId::FOLDER_JSON,
            include_bytes!("../../assets/charmed_icons/folder_json.b64"),
        ),
        (
            IconId::FOLDER_JSON_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_json_open.b64"),
        ),
        (
            IconId::FOLDER_LAYOUT,
            include_bytes!("../../assets/charmed_icons/folder_layout.b64"),
        ),
        (
            IconId::FOLDER_LAYOUT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_layout_open.b64"),
        ),
        (
            IconId::FOLDER_LIB,
            include_bytes!("../../assets/charmed_icons/folder_lib.b64"),
        ),
        (
            IconId::FOLDER_LIB_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_lib_open.b64"),
        ),
        (
            IconId::FOLDER_LUAU,
            include_bytes!("../../assets/charmed_icons/folder_luau.b64"),
        ),
        (
            IconId::FOLDER_LUAU_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_luau_open.b64"),
        ),
        (
            IconId::FOLDER_LUNE,
            include_bytes!("../../assets/charmed_icons/folder_lune.b64"),
        ),
        (
            IconId::FOLDER_LUNE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_lune_open.b64"),
        ),
        (
            IconId::FOLDER_MARKETING,
            include_bytes!("../../assets/charmed_icons/folder_marketing.b64"),
        ),
        (
            IconId::FOLDER_MARKETING_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_marketing_open.b64"),
        ),
        (
            IconId::FOLDER_MIDDLEWARE,
            include_bytes!("../../assets/charmed_icons/folder_middleware.b64"),
        ),
        (
            IconId::FOLDER_MIDDLEWARE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_middleware_open.b64"),
        ),
        (
            IconId::FOLDER_MODEL,
            include_bytes!("../../assets/charmed_icons/folder_model.b64"),
        ),
        (
            IconId::FOLDER_MODEL_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_model_open.b64"),
        ),
        (
            IconId::FOLDER_MODULE,
            include_bytes!("../../assets/charmed_icons/folder_module.b64"),
        ),
        (
            IconId::FOLDER_MODULE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_module_open.b64"),
        ),
        (
            IconId::FOLDER_NODE,
            include_bytes!("../../assets/charmed_icons/folder_node.b64"),
        ),
        (
            IconId::FOLDER_NODE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_node_open.b64"),
        ),
        (
            IconId::FOLDER_NUXT,
            include_bytes!("../../assets/charmed_icons/folder_nuxt.b64"),
        ),
        (
            IconId::FOLDER_NUXT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_nuxt_open.b64"),
        ),
        (
            IconId::FOLDER_PACKAGE,
            include_bytes!("../../assets/charmed_icons/folder_package.b64"),
        ),
        (
            IconId::FOLDER_PACKAGE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_package_open.b64"),
        ),
        (
            IconId::FOLDER_PAGE,
            include_bytes!("../../assets/charmed_icons/folder_page.b64"),
        ),
        (
            IconId::FOLDER_PAGE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_page_open.b64"),
        ),
        (
            IconId::FOLDER_PROVIDER,
            include_bytes!("../../assets/charmed_icons/folder_provider.b64"),
        ),
        (
            IconId::FOLDER_PROVIDER_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_provider_open.b64"),
        ),
        (
            IconId::FOLDER_ROBLOX,
            include_bytes!("../../assets/charmed_icons/folder_roblox.b64"),
        ),
        (
            IconId::FOLDER_ROBLOX_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_roblox_open.b64"),
        ),
        (
            IconId::FOLDER_ROUTES,
            include_bytes!("../../assets/charmed_icons/folder_routes.b64"),
        ),
        (
            IconId::FOLDER_ROUTES_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_routes_open.b64"),
        ),
        (
            IconId::FOLDER_SCRIPT,
            include_bytes!("../../assets/charmed_icons/folder_script.b64"),
        ),
        (
            IconId::FOLDER_SCRIPT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_script_open.b64"),
        ),
        (
            IconId::FOLDER_SERVER,
            include_bytes!("../../assets/charmed_icons/folder_server.b64"),
        ),
        (
            IconId::FOLDER_SERVER_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_server_open.b64"),
        ),
        (
            IconId::FOLDER_SERVICE,
            include_bytes!("../../assets/charmed_icons/folder_service.b64"),
        ),
        (
            IconId::FOLDER_SERVICE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_service_open.b64"),
        ),
        (
            IconId::FOLDER_SOURCE,
            include_bytes!("../../assets/charmed_icons/folder_source.b64"),
        ),
        (
            IconId::FOLDER_SOURCE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_source_open.b64"),
        ),
        (
            IconId::FOLDER_STORYBOOK,
            include_bytes!("../../assets/charmed_icons/folder_storybook.b64"),
        ),
        (
            IconId::FOLDER_STORYBOOK_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_storybook_open.b64"),
        ),
        (
            IconId::FOLDER_STYLES,
            include_bytes!("../../assets/charmed_icons/folder_styles.b64"),
        ),
        (
            IconId::FOLDER_STYLES_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_styles_open.b64"),
        ),
        (
            IconId::FOLDER_SVG,
            include_bytes!("../../assets/charmed_icons/folder_svg.b64"),
        ),
        (
            IconId::FOLDER_SVG_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_svg_open.b64"),
        ),
        (
            IconId::FOLDER_TEMP,
            include_bytes!("../../assets/charmed_icons/folder_temp.b64"),
        ),
        (
            IconId::FOLDER_TEMP_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_temp_open.b64"),
        ),
        (
            IconId::FOLDER_TEMPLATE,
            include_bytes!("../../assets/charmed_icons/folder_template.b64"),
        ),
        (
            IconId::FOLDER_TEMPLATE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_template_open.b64"),
        ),
        (
            IconId::FOLDER_TEST,
            include_bytes!("../../assets/charmed_icons/folder_test.b64"),
        ),
        (
            IconId::FOLDER_TEST_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_test_open.b64"),
        ),
        (
            IconId::FOLDER_TYPES,
            include_bytes!("../../assets/charmed_icons/folder_types.b64"),
        ),
        (
            IconId::FOLDER_TYPES_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_types_open.b64"),
        ),
        (
            IconId::FOLDER_TYPESCRIPT,
            include_bytes!("../../assets/charmed_icons/folder_typescript.b64"),
        ),
        (
            IconId::FOLDER_TYPESCRIPT_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_typescript_open.b64"),
        ),
        (
            IconId::FOLDER_UTIL,
            include_bytes!("../../assets/charmed_icons/folder_util.b64"),
        ),
        (
            IconId::FOLDER_UTIL_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_util_open.b64"),
        ),
        (
            IconId::FOLDER_VIDEO,
            include_bytes!("../../assets/charmed_icons/folder_video.b64"),
        ),
        (
            IconId::FOLDER_VIDEO_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_video_open.b64"),
        ),
        (
            IconId::FOLDER_VSCODE,
            include_bytes!("../../assets/charmed_icons/folder_vscode.b64"),
        ),
        (
            IconId::FOLDER_VSCODE_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_vscode_open.b64"),
        ),
        (
            IconId::FOLDER_WEB,
            include_bytes!("../../assets/charmed_icons/folder_web.b64"),
        ),
        (
            IconId::FOLDER_WEB_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_web_open.b64"),
        ),
        (
            IconId::FOLDER_YARN,
            include_bytes!("../../assets/charmed_icons/folder_yarn.b64"),
        ),
        (
            IconId::FOLDER_YARN_OPEN,
            include_bytes!("../../assets/charmed_icons/folder_yarn_open.b64"),
        ),
        (
            IconId::FONT,
            include_bytes!("../../assets/charmed_icons/font.b64"),
        ),
        (
            IconId::FORTRAN_FIXED,
            include_bytes!("../../assets/charmed_icons/fortran-fixed.b64"),
        ),
        (
            IconId::FORTRAN,
            include_bytes!("../../assets/charmed_icons/fortran.b64"),
        ),
        (
            IconId::GIT,
            include_bytes!("../../assets/charmed_icons/git.b64"),
        ),
        (
            IconId::GLEAM,
            include_bytes!("../../assets/charmed_icons/gleam.b64"),
        ),
        (
            IconId::GO_MOD,
            include_bytes!("../../assets/charmed_icons/go-mod.b64"),
        ),
        (
            IconId::GO,
            include_bytes!("../../assets/charmed_icons/go.b64"),
        ),
        (
            IconId::GODOT_ASSETS,
            include_bytes!("../../assets/charmed_icons/godot-assets.b64"),
        ),
        (
            IconId::GODOT,
            include_bytes!("../../assets/charmed_icons/godot.b64"),
        ),
        (
            IconId::HCL,
            include_bytes!("../../assets/charmed_icons/hcl.b64"),
        ),
        (
            IconId::HTML,
            include_bytes!("../../assets/charmed_icons/html.b64"),
        ),
        (
            IconId::IMAGE,
            include_bytes!("../../assets/charmed_icons/image.b64"),
        ),
        (
            IconId::JAVA,
            include_bytes!("../../assets/charmed_icons/java.b64"),
        ),
        (
            IconId::JAVASCRIPT_CONFIG,
            include_bytes!("../../assets/charmed_icons/javascript-config.b64"),
        ),
        (
            IconId::JAVASCRIPT,
            include_bytes!("../../assets/charmed_icons/javascript.b64"),
        ),
        (
            IconId::JSON,
            include_bytes!("../../assets/charmed_icons/json.b64"),
        ),
        (
            IconId::JULIA,
            include_bytes!("../../assets/charmed_icons/julia.b64"),
        ),
        (
            IconId::JUST,
            include_bytes!("../../assets/charmed_icons/just.b64"),
        ),
        (
            IconId::KEY,
            include_bytes!("../../assets/charmed_icons/key.b64"),
        ),
        (
            IconId::KOTLIN,
            include_bytes!("../../assets/charmed_icons/kotlin.b64"),
        ),
        (
            IconId::LATEX,
            include_bytes!("../../assets/charmed_icons/latex.b64"),
        ),
        (
            IconId::LICENSE,
            include_bytes!("../../assets/charmed_icons/license.b64"),
        ),
        (
            IconId::LOCK,
            include_bytes!("../../assets/charmed_icons/lock.b64"),
        ),
        (
            IconId::LUA_CONFIG,
            include_bytes!("../../assets/charmed_icons/lua-config.b64"),
        ),
        (
            IconId::LUA,
            include_bytes!("../../assets/charmed_icons/lua.b64"),
        ),
        (
            IconId::LUAU_CONFIG,
            include_bytes!("../../assets/charmed_icons/lua-config.b64"),
        ),
        (
            IconId::LUAU_DEF,
            include_bytes!("../../assets/charmed_icons/luau-def.b64"),
        ),
        (
            IconId::LUAU,
            include_bytes!("../../assets/charmed_icons/lua.b64"),
        ),
        (
            IconId::MAKEFILE,
            include_bytes!("../../assets/charmed_icons/makefile.b64"),
        ),
        (
            IconId::MARKDOWN,
            include_bytes!("../../assets/charmed_icons/markdown.b64"),
        ),
        (
            IconId::MARKDOWNX,
            include_bytes!("../../assets/charmed_icons/markdownx.b64"),
        ),
        (
            IconId::NEXT,
            include_bytes!("../../assets/charmed_icons/next.b64"),
        ),
        (
            IconId::NIM,
            include_bytes!("../../assets/charmed_icons/nim.b64"),
        ),
        (
            IconId::NIX,
            include_bytes!("../../assets/charmed_icons/nix.b64"),
        ),
        (
            IconId::NODE,
            include_bytes!("../../assets/charmed_icons/node.b64"),
        ),
        (
            IconId::NPM_LOCK,
            include_bytes!("../../assets/charmed_icons/npm-lock.b64"),
        ),
        (
            IconId::NPM,
            include_bytes!("../../assets/charmed_icons/npm.b64"),
        ),
        (
            IconId::NUXT,
            include_bytes!("../../assets/charmed_icons/nuxt.b64"),
        ),
        (
            IconId::ODIN,
            include_bytes!("../../assets/charmed_icons/odin.b64"),
        ),
        (
            IconId::PACKAGE_CONFIG,
            include_bytes!("../../assets/charmed_icons/package-config.b64"),
        ),
        (
            IconId::PACKAGE_LOCK,
            include_bytes!("../../assets/charmed_icons/package-lock.b64"),
        ),
        (
            IconId::PCSS,
            include_bytes!("../../assets/charmed_icons/pcss.b64"),
        ),
        (
            IconId::PDF,
            include_bytes!("../../assets/charmed_icons/pdf.b64"),
        ),
        (
            IconId::PERL,
            include_bytes!("../../assets/charmed_icons/perl.b64"),
        ),
        (
            IconId::PHP,
            include_bytes!("../../assets/charmed_icons/php.b64"),
        ),
        (
            IconId::POWERSHELL,
            include_bytes!("../../assets/charmed_icons/powershell.b64"),
        ),
        (
            IconId::PYTHON,
            include_bytes!("../../assets/charmed_icons/python.b64"),
        ),
        (
            IconId::REACT_TYPESCRIPT,
            include_bytes!("../../assets/charmed_icons/react-typescript.b64"),
        ),
        (
            IconId::REACT,
            include_bytes!("../../assets/charmed_icons/react.b64"),
        ),
        (
            IconId::README,
            include_bytes!("../../assets/charmed_icons/readme.b64"),
        ),
        (
            IconId::ROBLOX_CONFIG,
            include_bytes!("../../assets/charmed_icons/roblox-config.b64"),
        ),
        (
            IconId::ROBLOX_LOCK,
            include_bytes!("../../assets/charmed_icons/roblox-lock.b64"),
        ),
        (
            IconId::ROBLOX_MODEL,
            include_bytes!("../../assets/charmed_icons/roblox-model.b64"),
        ),
        (
            IconId::ROBLOX,
            include_bytes!("../../assets/charmed_icons/roblox.b64"),
        ),
        (
            IconId::RUBY,
            include_bytes!("../../assets/charmed_icons/ruby.b64"),
        ),
        (
            IconId::RUST_CONFIG,
            include_bytes!("../../assets/charmed_icons/rust-config.b64"),
        ),
        (
            IconId::RUST,
            include_bytes!("../../assets/charmed_icons/rust.b64"),
        ),
        (
            IconId::SCALA,
            include_bytes!("../../assets/charmed_icons/scala.b64"),
        ),
        (
            IconId::SCSS,
            include_bytes!("../../assets/charmed_icons/scss.b64"),
        ),
        (
            IconId::SECURITY,
            include_bytes!("../../assets/charmed_icons/security.b64"),
        ),
        (
            IconId::SHELL,
            include_bytes!("../../assets/charmed_icons/shell.b64"),
        ),
        (
            IconId::STORYBOOK,
            include_bytes!("../../assets/charmed_icons/storybook.b64"),
        ),
        (
            IconId::SVELTE,
            include_bytes!("../../assets/charmed_icons/svelte.b64"),
        ),
        (
            IconId::SVG,
            include_bytes!("../../assets/charmed_icons/svg.b64"),
        ),
        (
            IconId::SWIFT,
            include_bytes!("../../assets/charmed_icons/swift.b64"),
        ),
        (
            IconId::TAILWIND,
            include_bytes!("../../assets/charmed_icons/tailwind.b64"),
        ),
        (
            IconId::TERRAFORM,
            include_bytes!("../../assets/charmed_icons/terraform.b64"),
        ),
        (
            IconId::TEST_BLUE,
            include_bytes!("../../assets/charmed_icons/test-blue.b64"),
        ),
        (
            IconId::TEST_TEAL,
            include_bytes!("../../assets/charmed_icons/test-teal.b64"),
        ),
        (
            IconId::TEST_YELLOW,
            include_bytes!("../../assets/charmed_icons/test-yellow.b64"),
        ),
        (
            IconId::TEXT,
            include_bytes!("../../assets/charmed_icons/text.b64"),
        ),
        (
            IconId::TODO,
            include_bytes!("../../assets/charmed_icons/todo.b64"),
        ),
        (
            IconId::TOML,
            include_bytes!("../../assets/charmed_icons/toml.b64"),
        ),
        (
            IconId::TYPESCRIPT_CONFIG,
            include_bytes!("../../assets/charmed_icons/typescript-config.b64"),
        ),
        (
            IconId::TYPESCRIPT_DEF,
            include_bytes!("../../assets/charmed_icons/typescript-def.b64"),
        ),
        (
            IconId::TYPESCRIPT,
            include_bytes!("../../assets/charmed_icons/typescript.b64"),
        ),
        (
            IconId::VIDEO,
            include_bytes!("../../assets/charmed_icons/video.b64"),
        ),
        (
            IconId::VISUAL_STUDIO,
            include_bytes!("../../assets/charmed_icons/visual-studio.b64"),
        ),
        (
            IconId::VITE,
            include_bytes!("../../assets/charmed_icons/vite.b64"),
        ),
        (
            IconId::VSCODE,
            include_bytes!("../../assets/charmed_icons/vscode.b64"),
        ),
        (
            IconId::VUE,
            include_bytes!("../../assets/charmed_icons/vue.b64"),
        ),
        (
            IconId::WALLY_LOCK,
            include_bytes!("../../assets/charmed_icons/wally-lock.b64"),
        ),
        (
            IconId::WALLY,
            include_bytes!("../../assets/charmed_icons/wally.b64"),
        ),
        (
            IconId::WEB_ASSEMBLY,
            include_bytes!("../../assets/charmed_icons/web-assembly.b64"),
        ),
        (
            IconId::WORKFLOW,
            include_bytes!("../../assets/charmed_icons/workflow.b64"),
        ),
        (
            IconId::XML,
            include_bytes!("../../assets/charmed_icons/xml.b64"),
        ),
        (
            IconId::YAML,
            include_bytes!("../../assets/charmed_icons/yaml.b64"),
        ),
        (
            IconId::YARN_LOCK,
            include_bytes!("../../assets/charmed_icons/yarn-lock.b64"),
        ),
        (
            IconId::YARN,
            include_bytes!("../../assets/charmed_icons/yarn.b64"),
        ),
        (
            IconId::ZIG,
            include_bytes!("../../assets/charmed_icons/zig.b64"),
        ),
        (
            IconId::ZIP,
            include_bytes!("../../assets/charmed_icons/zip.b64"),
        ),
    ];
}
