use crate::{
    icons::{IconId, IconTheme},
    models::FileFormat,
};

#[derive(Debug, Default)]
pub struct JetBrainsIconTheme;

impl IconTheme for JetBrainsIconTheme {
    const COLLAPSED_ICON: &'static [u8] = include_bytes!("../../assets/jetbrains_icons/folder.b64");
    const EXPANDED_ICON: &'static [u8] = include_bytes!("../../assets/jetbrains_icons/folder.b64");
    const EXTENSION_ICONS: &'static [(IconId, &'static [u8])] = &[
        (
            IconId::from_format(FileFormat::Unknown),
            include_bytes!("../../assets/jetbrains_icons/anyType.b64"),
        ),
        (
            IconId::from_format(FileFormat::ActionScript),
            include_bytes!("../../assets/jetbrains_icons/actionScript.b64"),
        ),
        (
            IconId::from_format(FileFormat::Archive),
            include_bytes!("../../assets/jetbrains_icons/archive.b64"),
        ),
        (
            IconId::from_format(FileFormat::Beam),
            include_bytes!("../../assets/jetbrains_icons/beam.b64"),
        ),
        (
            IconId::from_format(FileFormat::C),
            include_bytes!("../../assets/jetbrains_icons/c.b64"),
        ),
        (
            IconId::from_format(FileFormat::C3),
            include_bytes!("../../assets/jetbrains_icons/c3.b64"),
        ),
        (
            IconId::from_format(FileFormat::CHeader),
            include_bytes!("../../assets/jetbrains_icons/h.b64"),
        ),
        (
            IconId::from_format(FileFormat::Clojure),
            include_bytes!("../../assets/jetbrains_icons/clojure.b64"),
        ),
        (
            IconId::from_format(FileFormat::CMake),
            include_bytes!("../../assets/jetbrains_icons/CMake.b64"),
        ),
        (
            IconId::from_format(FileFormat::Config),
            include_bytes!("../../assets/jetbrains_icons/config.b64"),
        ),
        (
            IconId::from_format(FileFormat::Cpp),
            include_bytes!("../../assets/jetbrains_icons/cpp.b64"),
        ),
        (
            IconId::from_format(FileFormat::CSharp),
            include_bytes!("../../assets/jetbrains_icons/cs.b64"),
        ),
        (
            IconId::from_format(FileFormat::CsHtml),
            include_bytes!("../../assets/jetbrains_icons/cshtml.b64"),
        ),
        (
            IconId::from_format(FileFormat::CsProj),
            include_bytes!("../../assets/jetbrains_icons/csproj.b64"),
        ),
        (
            IconId::from_format(FileFormat::Css),
            include_bytes!("../../assets/jetbrains_icons/css.b64"),
        ),
        (
            IconId::from_format(FileFormat::Csv),
            include_bytes!("../../assets/jetbrains_icons/csv.b64"),
        ),
        (
            IconId::from_format(FileFormat::Cuda),
            include_bytes!("../../assets/jetbrains_icons/cu.b64"),
        ),
        (
            IconId::from_format(FileFormat::CudaHeader),
            include_bytes!("../../assets/jetbrains_icons/cuh.b64"),
        ),
        (
            IconId::from_format(FileFormat::Dart),
            include_bytes!("../../assets/jetbrains_icons/dart.b64"),
        ),
        (
            IconId::from_format(FileFormat::Database),
            include_bytes!("../../assets/jetbrains_icons/dbms.b64"),
        ),
        (
            IconId::from_format(FileFormat::Eex),
            include_bytes!("../../assets/jetbrains_icons/eex.b64"),
        ),
        (
            IconId::from_format(FileFormat::Elixir),
            include_bytes!("../../assets/jetbrains_icons/elixir.b64"),
        ),
        (
            IconId::from_format(FileFormat::Erb),
            include_bytes!("../../assets/jetbrains_icons/erbFile.b64"),
        ),
        (
            IconId::from_format(FileFormat::Erlang),
            include_bytes!("../../assets/jetbrains_icons/erlang.b64"),
        ),
        (
            IconId::from_format(FileFormat::Font),
            include_bytes!("../../assets/jetbrains_icons/font.b64"),
        ),
        (
            IconId::from_format(FileFormat::Gleam),
            include_bytes!("../../assets/jetbrains_icons/gleam.b64"),
        ),
        (
            IconId::from_format(FileFormat::Go),
            include_bytes!("../../assets/jetbrains_icons/go.b64"),
        ),
        (
            IconId::from_format(FileFormat::GraphQl),
            include_bytes!("../../assets/jetbrains_icons/graphql.b64"),
        ),
        (
            IconId::from_format(FileFormat::Handlebars),
            include_bytes!("../../assets/jetbrains_icons/handlebarsJson.b64"),
        ),
        (
            IconId::from_format(FileFormat::Haskell),
            include_bytes!("../../assets/jetbrains_icons/haskell.b64"),
        ),
        (
            IconId::from_format(FileFormat::Hcl),
            include_bytes!("../../assets/jetbrains_icons/hcl.b64"),
        ),
        (
            IconId::from_format(FileFormat::Html),
            include_bytes!("../../assets/jetbrains_icons/html.b64"),
        ),
        (
            IconId::from_format(FileFormat::Http),
            include_bytes!("../../assets/jetbrains_icons/http.b64"),
        ),
        (
            IconId::from_format(FileFormat::Image),
            include_bytes!("../../assets/jetbrains_icons/image.b64"),
        ),
        (
            IconId::from_format(FileFormat::Ino),
            include_bytes!("../../assets/jetbrains_icons/ino.b64"),
        ),
        (
            IconId::from_format(FileFormat::Java),
            include_bytes!("../../assets/jetbrains_icons/java.b64"),
        ),
        (
            IconId::from_format(FileFormat::JavaScript),
            include_bytes!("../../assets/jetbrains_icons/javaScript.b64"),
        ),
        (
            IconId::from_format(FileFormat::Json),
            include_bytes!("../../assets/jetbrains_icons/json.b64"),
        ),
        (
            IconId::from_format(FileFormat::Jsx),
            include_bytes!("../../assets/jetbrains_icons/jsx.b64"),
        ),
        (
            IconId::from_format(FileFormat::Jupyter),
            include_bytes!("../../assets/jetbrains_icons/jupyter.b64"),
        ),
        (
            IconId::from_format(FileFormat::Kotlin),
            include_bytes!("../../assets/jetbrains_icons/kotlin.b64"),
        ),
        (
            IconId::from_format(FileFormat::KotlinScript),
            include_bytes!("../../assets/jetbrains_icons/kotlinScript.b64"),
        ),
        (
            IconId::from_format(FileFormat::Less),
            include_bytes!("../../assets/jetbrains_icons/less.b64"),
        ),
        (
            IconId::from_format(FileFormat::Lock),
            include_bytes!("../../assets/jetbrains_icons/lock.b64"),
        ),
        (
            IconId::from_format(FileFormat::Lua),
            include_bytes!("../../assets/jetbrains_icons/lua.b64"),
        ),
        (
            IconId::from_format(FileFormat::Markdown),
            include_bytes!("../../assets/jetbrains_icons/markdown.b64"),
        ),
        (
            IconId::from_format(FileFormat::Mdx),
            include_bytes!("../../assets/jetbrains_icons/mdx.b64"),
        ),
        (
            IconId::from_format(FileFormat::OCaml),
            include_bytes!("../../assets/jetbrains_icons/ml.b64"),
        ),
        (
            IconId::from_format(FileFormat::OCamlInterface),
            include_bytes!("../../assets/jetbrains_icons/mli.b64"),
        ),
        (
            IconId::from_format(FileFormat::Opam),
            include_bytes!("../../assets/jetbrains_icons/opam.b64"),
        ),
        (
            IconId::from_format(FileFormat::Php),
            include_bytes!("../../assets/jetbrains_icons/php.b64"),
        ),
        (
            IconId::from_format(FileFormat::Properties),
            include_bytes!("../../assets/jetbrains_icons/properties.b64"),
        ),
        (
            IconId::from_format(FileFormat::Proto),
            include_bytes!("../../assets/jetbrains_icons/protoFile.b64"),
        ),
        (
            IconId::from_format(FileFormat::Python),
            include_bytes!("../../assets/jetbrains_icons/python.b64"),
        ),
        (
            IconId::from_format(FileFormat::Rake),
            include_bytes!("../../assets/jetbrains_icons/rakeTask.b64"),
        ),
        (
            IconId::from_format(FileFormat::Rego),
            include_bytes!("../../assets/jetbrains_icons/rego.b64"),
        ),
        (
            IconId::from_format(FileFormat::Ruby),
            include_bytes!("../../assets/jetbrains_icons/ruby.b64"),
        ),
        (
            IconId::from_format(FileFormat::Rust),
            include_bytes!("../../assets/jetbrains_icons/rustFile.b64"),
        ),
        (
            IconId::from_format(FileFormat::Scala),
            include_bytes!("../../assets/jetbrains_icons/scala.b64"),
        ),
        (
            IconId::from_format(FileFormat::Scss),
            include_bytes!("../../assets/jetbrains_icons/scss.b64"),
        ),
        (
            IconId::from_format(FileFormat::Shell),
            include_bytes!("../../assets/jetbrains_icons/shell.b64"),
        ),
        (
            IconId::from_format(FileFormat::Slim),
            include_bytes!("../../assets/jetbrains_icons/slim.b64"),
        ),
        (
            IconId::from_format(FileFormat::Solution),
            include_bytes!("../../assets/jetbrains_icons/solution.b64"),
        ),
        (
            IconId::from_format(FileFormat::Sql),
            include_bytes!("../../assets/jetbrains_icons/sql.b64"),
        ),
        (
            IconId::from_format(FileFormat::Svelte),
            include_bytes!("../../assets/jetbrains_icons/svelte.b64"),
        ),
        (
            IconId::from_format(FileFormat::Swift),
            include_bytes!("../../assets/jetbrains_icons/swift.b64"),
        ),
        (
            IconId::from_format(FileFormat::Terraform),
            include_bytes!("../../assets/jetbrains_icons/terraform.b64"),
        ),
        (
            IconId::from_format(FileFormat::Text),
            include_bytes!("../../assets/jetbrains_icons/text.b64"),
        ),
        (
            IconId::from_format(FileFormat::Toml),
            include_bytes!("../../assets/jetbrains_icons/toml.b64"),
        ),
        (
            IconId::from_format(FileFormat::Tsx),
            include_bytes!("../../assets/jetbrains_icons/tsx.b64"),
        ),
        (
            IconId::from_format(FileFormat::TypeScript),
            include_bytes!("../../assets/jetbrains_icons/typeScript.b64"),
        ),
        (
            IconId::from_format(FileFormat::VLang),
            include_bytes!("../../assets/jetbrains_icons/vlang.b64"),
        ),
        (
            IconId::from_format(FileFormat::Vue),
            include_bytes!("../../assets/jetbrains_icons/vueJs.b64"),
        ),
        (
            IconId::from_format(FileFormat::Xml),
            include_bytes!("../../assets/jetbrains_icons/xml.b64"),
        ),
        (
            IconId::from_format(FileFormat::Yaml),
            include_bytes!("../../assets/jetbrains_icons/yaml.b64"),
        ),
        (
            IconId::from_format(FileFormat::Zig),
            include_bytes!("../../assets/jetbrains_icons/zig.b64"),
        ),
        (
            IconId::from_format(FileFormat::Angular),
            include_bytes!("../../assets/jetbrains_icons/angularJS.b64"),
        ),
        (
            IconId::from_format(FileFormat::Application),
            include_bytes!("../../assets/jetbrains_icons/application.b64"),
        ),
        (
            IconId::from_format(FileFormat::Biome),
            include_bytes!("../../assets/jetbrains_icons/biomejs.b64"),
        ),
        (
            IconId::from_format(FileFormat::Bun),
            include_bytes!("../../assets/jetbrains_icons/bun.b64"),
        ),
        (
            IconId::from_format(FileFormat::C3Interface),
            include_bytes!("../../assets/jetbrains_icons/c3Interface.b64"),
        ),
        (
            IconId::from_format(FileFormat::C3Library),
            include_bytes!("../../assets/jetbrains_icons/c3Library.b64"),
        ),
        (
            IconId::from_format(FileFormat::C3Test),
            include_bytes!("../../assets/jetbrains_icons/c3Test.b64"),
        ),
        (
            IconId::from_format(FileFormat::Cargo),
            include_bytes!("../../assets/jetbrains_icons/cargo.b64"),
        ),
        (
            IconId::from_format(FileFormat::CargoLock),
            include_bytes!("../../assets/jetbrains_icons/cargoLock.b64"),
        ),
        (
            IconId::from_format(FileFormat::Docker),
            include_bytes!("../../assets/jetbrains_icons/docker.b64"),
        ),
        (
            IconId::from_format(FileFormat::Dune),
            include_bytes!("../../assets/jetbrains_icons/dune.b64"),
        ),
        (
            IconId::from_format(FileFormat::EditorConfig),
            include_bytes!("../../assets/jetbrains_icons/editorConfig.b64"),
        ),
        (
            IconId::from_format(FileFormat::Eslint),
            include_bytes!("../../assets/jetbrains_icons/eslint.b64"),
        ),
        (
            IconId::from_format(FileFormat::GitIgnore),
            include_bytes!("../../assets/jetbrains_icons/gitignore.b64"),
        ),
        (
            IconId::from_format(FileFormat::GoMod),
            include_bytes!("../../assets/jetbrains_icons/goMod.b64"),
        ),
        (
            IconId::from_format(FileFormat::GoSum),
            include_bytes!("../../assets/jetbrains_icons/goSum.b64"),
        ),
        (
            IconId::from_format(FileFormat::GoWork),
            include_bytes!("../../assets/jetbrains_icons/goWork.b64"),
        ),
        (
            IconId::from_format(FileFormat::JsTest),
            include_bytes!("../../assets/jetbrains_icons/jsTest.b64"),
        ),
        (
            IconId::from_format(FileFormat::JsxTest),
            include_bytes!("../../assets/jetbrains_icons/jsxTest.b64"),
        ),
        (
            IconId::from_format(FileFormat::Module),
            include_bytes!("../../assets/jetbrains_icons/module.b64"),
        ),
        (
            IconId::from_format(FileFormat::NodeJs),
            include_bytes!("../../assets/jetbrains_icons/nodejs.b64"),
        ),
        (
            IconId::from_format(FileFormat::Npm),
            include_bytes!("../../assets/jetbrains_icons/npm.b64"),
        ),
        (
            IconId::from_format(FileFormat::OpenTofu),
            include_bytes!("../../assets/jetbrains_icons/opentofu.b64"),
        ),
        (
            IconId::from_format(FileFormat::Pnpm),
            include_bytes!("../../assets/jetbrains_icons/pnpm.b64"),
        ),
        (
            IconId::from_format(FileFormat::PostCss),
            include_bytes!("../../assets/jetbrains_icons/postcss.b64"),
        ),
        (
            IconId::from_format(FileFormat::Prettier),
            include_bytes!("../../assets/jetbrains_icons/prettier.b64"),
        ),
        (
            IconId::from_format(FileFormat::ProjectProperties),
            include_bytes!("../../assets/jetbrains_icons/projectProperties.b64"),
        ),
        (
            IconId::from_format(FileFormat::Protobuf),
            include_bytes!("../../assets/jetbrains_icons/protobuf.b64"),
        ),
        (
            IconId::from_format(FileFormat::Tailwind),
            include_bytes!("../../assets/jetbrains_icons/tailwind.b64"),
        ),
        (
            IconId::from_format(FileFormat::TsTest),
            include_bytes!("../../assets/jetbrains_icons/tsTest.b64"),
        ),
        (
            IconId::from_format(FileFormat::TsxTest),
            include_bytes!("../../assets/jetbrains_icons/tsxTest.b64"),
        ),
        (
            IconId::from_format(FileFormat::Vercel),
            include_bytes!("../../assets/jetbrains_icons/vercel.b64"),
        ),
        (
            IconId::from_format(FileFormat::Vite),
            include_bytes!("../../assets/jetbrains_icons/vite.b64"),
        ),
        (
            IconId::from_format(FileFormat::Yarn),
            include_bytes!("../../assets/jetbrains_icons/yarn.b64"),
        ),
    ];
}
