use crate::{
    icons::{IconId, IconTheme},
    models::FileExtension,
};

#[derive(Debug, Default)]
pub struct JetBrainsIconTheme;

impl IconTheme for JetBrainsIconTheme {
    const COLLAPSED_ICON: &'static [u8] = include_bytes!("../../assets/jetbrains_icons/folder.b64");
    const EXPANDED_ICON: &'static [u8] = include_bytes!("../../assets/jetbrains_icons/folder.b64");
    const EXTENSION_ICONS: &'static [(IconId, &'static [u8])] = &[
        (
            IconId::from_extension(FileExtension::Unknown),
            include_bytes!("../../assets/jetbrains_icons/anyType.b64"),
        ),
        (
            IconId::from_extension(FileExtension::ActionScript),
            include_bytes!("../../assets/jetbrains_icons/actionScript.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Archive),
            include_bytes!("../../assets/jetbrains_icons/archive.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Beam),
            include_bytes!("../../assets/jetbrains_icons/beam.b64"),
        ),
        (
            IconId::from_extension(FileExtension::C),
            include_bytes!("../../assets/jetbrains_icons/c.b64"),
        ),
        (
            IconId::from_extension(FileExtension::C3),
            include_bytes!("../../assets/jetbrains_icons/c3.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CHeader),
            include_bytes!("../../assets/jetbrains_icons/h.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Clojure),
            include_bytes!("../../assets/jetbrains_icons/clojure.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CMake),
            include_bytes!("../../assets/jetbrains_icons/CMake.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Config),
            include_bytes!("../../assets/jetbrains_icons/config.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Cpp),
            include_bytes!("../../assets/jetbrains_icons/cpp.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CSharp),
            include_bytes!("../../assets/jetbrains_icons/cs.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CsHtml),
            include_bytes!("../../assets/jetbrains_icons/cshtml.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CsProj),
            include_bytes!("../../assets/jetbrains_icons/csproj.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Css),
            include_bytes!("../../assets/jetbrains_icons/css.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Csv),
            include_bytes!("../../assets/jetbrains_icons/csv.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Cuda),
            include_bytes!("../../assets/jetbrains_icons/cu.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CudaHeader),
            include_bytes!("../../assets/jetbrains_icons/cuh.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Dart),
            include_bytes!("../../assets/jetbrains_icons/dart.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Database),
            include_bytes!("../../assets/jetbrains_icons/dbms.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Eex),
            include_bytes!("../../assets/jetbrains_icons/eex.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Elixir),
            include_bytes!("../../assets/jetbrains_icons/elixir.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Erb),
            include_bytes!("../../assets/jetbrains_icons/erbFile.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Erlang),
            include_bytes!("../../assets/jetbrains_icons/erlang.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Font),
            include_bytes!("../../assets/jetbrains_icons/font.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Gleam),
            include_bytes!("../../assets/jetbrains_icons/gleam.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Go),
            include_bytes!("../../assets/jetbrains_icons/go.b64"),
        ),
        (
            IconId::from_extension(FileExtension::GraphQl),
            include_bytes!("../../assets/jetbrains_icons/graphql.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Handlebars),
            include_bytes!("../../assets/jetbrains_icons/handlebarsJson.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Haskell),
            include_bytes!("../../assets/jetbrains_icons/haskell.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Hcl),
            include_bytes!("../../assets/jetbrains_icons/hcl.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Html),
            include_bytes!("../../assets/jetbrains_icons/html.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Http),
            include_bytes!("../../assets/jetbrains_icons/http.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Image),
            include_bytes!("../../assets/jetbrains_icons/image.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Ino),
            include_bytes!("../../assets/jetbrains_icons/ino.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Java),
            include_bytes!("../../assets/jetbrains_icons/java.b64"),
        ),
        (
            IconId::from_extension(FileExtension::JavaScript),
            include_bytes!("../../assets/jetbrains_icons/javaScript.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Json),
            include_bytes!("../../assets/jetbrains_icons/json.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Jsx),
            include_bytes!("../../assets/jetbrains_icons/jsx.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Jupyter),
            include_bytes!("../../assets/jetbrains_icons/jupyter.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Kotlin),
            include_bytes!("../../assets/jetbrains_icons/kotlin.b64"),
        ),
        (
            IconId::from_extension(FileExtension::KotlinScript),
            include_bytes!("../../assets/jetbrains_icons/kotlinScript.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Less),
            include_bytes!("../../assets/jetbrains_icons/less.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Lock),
            include_bytes!("../../assets/jetbrains_icons/lock.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Lua),
            include_bytes!("../../assets/jetbrains_icons/lua.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Markdown),
            include_bytes!("../../assets/jetbrains_icons/markdown.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Mdx),
            include_bytes!("../../assets/jetbrains_icons/mdx.b64"),
        ),
        (
            IconId::from_extension(FileExtension::OCaml),
            include_bytes!("../../assets/jetbrains_icons/ml.b64"),
        ),
        (
            IconId::from_extension(FileExtension::OCamlInterface),
            include_bytes!("../../assets/jetbrains_icons/mli.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Opam),
            include_bytes!("../../assets/jetbrains_icons/opam.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Php),
            include_bytes!("../../assets/jetbrains_icons/php.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Properties),
            include_bytes!("../../assets/jetbrains_icons/properties.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Proto),
            include_bytes!("../../assets/jetbrains_icons/protoFile.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Python),
            include_bytes!("../../assets/jetbrains_icons/python.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Rake),
            include_bytes!("../../assets/jetbrains_icons/rakeTask.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Rego),
            include_bytes!("../../assets/jetbrains_icons/rego.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Ruby),
            include_bytes!("../../assets/jetbrains_icons/ruby.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Rust),
            include_bytes!("../../assets/jetbrains_icons/rust.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Scala),
            include_bytes!("../../assets/jetbrains_icons/scala.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Scss),
            include_bytes!("../../assets/jetbrains_icons/scss.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Shell),
            include_bytes!("../../assets/jetbrains_icons/shell.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Slim),
            include_bytes!("../../assets/jetbrains_icons/slim.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Solution),
            include_bytes!("../../assets/jetbrains_icons/solution.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Sql),
            include_bytes!("../../assets/jetbrains_icons/sql.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Svelte),
            include_bytes!("../../assets/jetbrains_icons/svelte.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Swift),
            include_bytes!("../../assets/jetbrains_icons/swift.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Terraform),
            include_bytes!("../../assets/jetbrains_icons/terraform.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Text),
            include_bytes!("../../assets/jetbrains_icons/text.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Toml),
            include_bytes!("../../assets/jetbrains_icons/toml.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Tsx),
            include_bytes!("../../assets/jetbrains_icons/tsx.b64"),
        ),
        (
            IconId::from_extension(FileExtension::TypeScript),
            include_bytes!("../../assets/jetbrains_icons/typeScript.b64"),
        ),
        (
            IconId::from_extension(FileExtension::VLang),
            include_bytes!("../../assets/jetbrains_icons/vlang.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Vue),
            include_bytes!("../../assets/jetbrains_icons/vueJs.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Xml),
            include_bytes!("../../assets/jetbrains_icons/xml.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Yaml),
            include_bytes!("../../assets/jetbrains_icons/yaml.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Zig),
            include_bytes!("../../assets/jetbrains_icons/zig.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Angular),
            include_bytes!("../../assets/jetbrains_icons/angularJS.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Application),
            include_bytes!("../../assets/jetbrains_icons/application.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Biome),
            include_bytes!("../../assets/jetbrains_icons/biomejs.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Bun),
            include_bytes!("../../assets/jetbrains_icons/bun.b64"),
        ),
        (
            IconId::from_extension(FileExtension::C3Interface),
            include_bytes!("../../assets/jetbrains_icons/c3Interface.b64"),
        ),
        (
            IconId::from_extension(FileExtension::C3Library),
            include_bytes!("../../assets/jetbrains_icons/c3Library.b64"),
        ),
        (
            IconId::from_extension(FileExtension::C3Test),
            include_bytes!("../../assets/jetbrains_icons/c3Test.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Cargo),
            include_bytes!("../../assets/jetbrains_icons/cargo.b64"),
        ),
        (
            IconId::from_extension(FileExtension::CargoLock),
            include_bytes!("../../assets/jetbrains_icons/cargoLock.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Docker),
            include_bytes!("../../assets/jetbrains_icons/docker.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Dune),
            include_bytes!("../../assets/jetbrains_icons/dune.b64"),
        ),
        (
            IconId::from_extension(FileExtension::EditorConfig),
            include_bytes!("../../assets/jetbrains_icons/editorConfig.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Eslint),
            include_bytes!("../../assets/jetbrains_icons/eslint.b64"),
        ),
        (
            IconId::from_extension(FileExtension::GitIgnore),
            include_bytes!("../../assets/jetbrains_icons/gitignore.b64"),
        ),
        (
            IconId::from_extension(FileExtension::GoMod),
            include_bytes!("../../assets/jetbrains_icons/goMod.b64"),
        ),
        (
            IconId::from_extension(FileExtension::GoSum),
            include_bytes!("../../assets/jetbrains_icons/goSum.b64"),
        ),
        (
            IconId::from_extension(FileExtension::GoWork),
            include_bytes!("../../assets/jetbrains_icons/goWork.b64"),
        ),
        (
            IconId::from_extension(FileExtension::JsTest),
            include_bytes!("../../assets/jetbrains_icons/jsTest.b64"),
        ),
        (
            IconId::from_extension(FileExtension::JsxTest),
            include_bytes!("../../assets/jetbrains_icons/jsxTest.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Module),
            include_bytes!("../../assets/jetbrains_icons/module.b64"),
        ),
        (
            IconId::from_extension(FileExtension::NodeJs),
            include_bytes!("../../assets/jetbrains_icons/nodejs.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Npm),
            include_bytes!("../../assets/jetbrains_icons/npm.b64"),
        ),
        (
            IconId::from_extension(FileExtension::OpenTofu),
            include_bytes!("../../assets/jetbrains_icons/opentofu.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Pnpm),
            include_bytes!("../../assets/jetbrains_icons/pnpm.b64"),
        ),
        (
            IconId::from_extension(FileExtension::PostCss),
            include_bytes!("../../assets/jetbrains_icons/postcss.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Prettier),
            include_bytes!("../../assets/jetbrains_icons/prettier.b64"),
        ),
        (
            IconId::from_extension(FileExtension::ProjectProperties),
            include_bytes!("../../assets/jetbrains_icons/projectProperties.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Protobuf),
            include_bytes!("../../assets/jetbrains_icons/protobuf.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Tailwind),
            include_bytes!("../../assets/jetbrains_icons/tailwind.b64"),
        ),
        (
            IconId::from_extension(FileExtension::TsTest),
            include_bytes!("../../assets/jetbrains_icons/tsTest.b64"),
        ),
        (
            IconId::from_extension(FileExtension::TsxTest),
            include_bytes!("../../assets/jetbrains_icons/tsxTest.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Vercel),
            include_bytes!("../../assets/jetbrains_icons/vercel.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Vite),
            include_bytes!("../../assets/jetbrains_icons/vite.b64"),
        ),
        (
            IconId::from_extension(FileExtension::Yarn),
            include_bytes!("../../assets/jetbrains_icons/yarn.b64"),
        ),
    ];
}
